### ISSUE TITLE
npm run dev generate error

### ISSUE THREAD

**Issue by sarzali07** [coreui/coreui-free-laravel-admin-template#52]
I got an error while installing coreui on the subdomain, 

> @coreui/coreui-free-laravel-admin-template@2.0.1 development /home/****
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/*****/node_modules/cross-env/src/index.js:23
    )
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/****/node_modules/cross-env/src/bin/cross-env.js:3:18)
    at Module._compile (module.js:570:32)

npm ERR! Linux 2.6.32-042stab145.3
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "development"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @coreui/coreui-free-laravel-admin-template@2.0.1 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @coreui/coreui-free-laravel-admin-template@2.0.1 development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @coreui/coreui-free-laravel-admin-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @coreui/coreui-free-laravel-admin-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @coreui/coreui-free-laravel-admin-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/****/npm-debug.log

**Comment by silicon-selenion** [comment]
What is your node version ?

**Comment by sarzali07** [comment]
Error rec now
NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

sh: webpack: command not found

Node version: v6.9.2

**Comment by silicon-selenion** [comment]
This is issue you can solve by upgrading your node version then 😉

**Comment by sarzali07** [comment]
node -v
v14.15.1
npm -v
6.14.9


/node_modules/yar                                                                                        gs/yargs.js:4
async function requiresNode8OrGreater () {}
      ^^^^^^^^

SyntaxError: Unexpected token function
    at NativeCompileCache._moduleCompile (/home/*********/backpanel/node_modules/v8-compile-cache/v8-compile-cache.js:240:                                                                                        18)
    at Module._compile (/home/*******/ba                                                                                        ckpanel/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/******/backpanel/                                                                                        node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/*********                                                                                       /backpanel/node_modules/yargs/index.js:5:15)
    at Module._compile (/home/************/ba                                                                                        ckpanel/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/*********/backpanel/                                                                                        node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/********                                                                                        /backpanel/node_modules/laravel-mix/src/config.js:1:92)
    at Module._compile (/home/***********/ba                                                                                        ckpanel/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/*********/backpanel/                                                                                        node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/**********                                                                                        /backpanel/node_modules/laravel-mix/src/index.js:27:17)
    at Module._compile (/home/*****/ba                                                                                        ckpanel/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

**Comment by sarzali07** [comment]
webpack -v
[webpack-cli] It looks like webpack is not installed.
✔ Would you like to install webpack -W? (That will run npm install -D webpack -W) (Y/n) · true
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #2: Expected string but got null
npm ERR! typeerror     at exports.findRequirement (/usr/local/lib/node_modules/npm/lib/install/deps.js:756:3)
npm ERR! typeerror     at findChild (/usr/local/lib/node_modules/npm/lib/install/deps.js:125:17)
npm ERR! typeerror     at computeMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:142:11)
npm ERR! typeerror     at Installer.normalizeCurrentTree (/usr/local/lib/node_modules/npm/lib/install.js:414:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install.js:368:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64
npm ERR! typeerror     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/call-limit/call-limit.js:28:43
npm ERR! typeerror     at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-22T15_16_06_163Z-debug.log
[webpack-cli] Action Interrupted, Please try once again or install webpack manually.

**Comment by sarzali07** [comment]
/usr/lib/node_modules/webpack-cli/node_modules/pkg-dir/index.js:5
const pkgDir = async cwd => {
                     ^^^

SyntaxError: Unexpected identifier
    at NativeCompileCache._moduleCompile (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/lib/node_modules/webpack-cli/node_modules/import-local/index.js:4:16)
    at Module._compile (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

**Comment by sarzali07** [comment]
0


Now above code resolve by this command sudo npm install cross-env

Now this error receive

node_modules/cross-env/src/index.js:23
    )
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/******/node_modules/cross-env/src/bin/cross-env.js:3:18)
